<?php
/**
 * @file
 * Paragraphs theme tester module.
 *
 * Adds module-provided themes for use in tests.
 */

/**
 * Implements hook_system_theme_info().
 */
function paragraphs_theme_tester_system_theme_info() {
  $path = backdrop_get_path('module', 'paragraphs_theme_tester');
  $themes['ptest_theme_1'] = $path . '/ptest_theme_1/ptest_theme_1.info';
  $themes['ptest_theme_2'] = $path . '/ptest_theme_2/ptest_theme_2.info';
  $themes['ptest_theme_3'] = $path . '/ptest_theme_3/ptest_theme_3.info';
  $themes['ptest_theme_4'] = $path . '/ptest_theme_4/ptest_theme_4.info';
  return $themes;
}
