<?php
/**
 * @file
 * Paragraphs library hook implementations and other functions.
 */

/**
 * Implements hook_config_info().
 */
function paragraphs_library_config_info() {
  $prefixes['paragraphs_library.type'] = [
    'name_key' => 'type',
    'label_key' => 'label',
    'group' => t('Paragraphs library types'),
  ];
  return $prefixes;
}

/**
 * Implements hook_entity_info().
 */
function paragraphs_library_entity_info() {
  $entity_info = [
    'paragraphs_library_item' => [
      'label' => t('Paragraphs library item'),
      'plural label' => t('Paragraphs library items'),
      'entity class' => 'ParagraphsLibraryItem',
      'controller class' => 'ParagraphsLibraryItemController',
      'base table' => 'paragraphs_library_item',
      'fieldable' => TRUE,
      'entity keys' => [
        'id' => 'paragraphs_library_id',
        'bundle' => 'type',
        'label' => 'title',
      ],
      'bundle keys' => [
        'bundle' => 'type',
      ],
      'bundles' => [],
      'view modes' => [
        // Provide a new view mode.
        'paragraphs_library_item' => [
          'label' => 'Paragraphs library item',
          'custom settings' => FALSE, // Use the default settings.
        ],
      ],
      'module' => 'paragraphs_library',

      // While this key is not defined in hook_entity_info(), we use it for
      // convenience, providing an easier way to check access outside the class.
      'access callback' => 'paragraphs_library_access',

      // This controller is used to display non Field API extra fields.
      'extra fields controller class' => 'EntityDefaultExtraFieldsController',

      // By including 'admin ui' we are telling Entity UI to create menu items
      // for viewing, adding, editing and deleting paragraphs_library entities.
      'admin ui' => [
        'path' => 'admin/content/paragraphs/library',
        'controller class' => 'EntityBundleableUIController',
        'file' => 'paragraphs_library.admin.inc',
        'menu wildcard' => '%paragraphs_library_item',
      ],

      // This tells Entity Plus to make the text entered in the entity
      // properties (e.g. title) available to i18n_string for translations.
      'i18n controller class' => 'EntityDefaultI18nStringController',
    ],
  ];

  // Bundles must provide a human readable name so we can create help and error
  // messages, and the path to attach Field admin pages to.
  // node_type_cache_reset();
  foreach (paragraphs_library_type_load() as $type) {
    $entity_info['paragraphs_library_item']['bundles'][$type->type] = [
      'label' => $type->label,
      'admin' => [
        'path' => 'admin/structure/paragraphs/library/types/%paragraphs_library_type',
        'real path' => 'admin/structure/paragraphs/library/types/' . str_replace('_', '-', $type->type),
        'bundle argument' => 5,
        'access arguments' => ['administer paragraphs_library types'],
      ],
    ];
  }

  return $entity_info;
}

/**
 * Implements hook.autoload_info().
 */
function paragraphs_library_autoload_info() {
  return [
    'ParagraphsLibraryItem' => 'paragraphs_library.class.inc',
    'ParagraphsLibraryItemController' => 'paragraphs_library.controller.inc',
    'views_handler_field_paragraphs_library_link_edit' => 'views/views_handler_field_paragraphs_library_link_edit.inc',
    'views_handler_field_paragraphs_library_link' => 'views/views_handler_field_paragraphs_library_link.inc',
    'views_handler_field_paragraphs_library_link_delete' => 'views/views_handler_field_paragraphs_library_link_delete.inc',
  ];
}

/**
 * Implements hook_menu().
 *
 */
function paragraphs_library_menu() {
  $items = [];

  $items['admin/content/paragraphs/library/add'] = [
    'title' => t('Add library item'),
    'description' => t('Create a new item for reuse in the Paragraphs library.'),
    'page callback' => 'paragraphs_library_type_choice',
    'access arguments' => ['create paragraphs_library_item entities'],
    'type' => MENU_LOCAL_ACTION,
  ];

  // Create paths to create Paragraphs library entities for each type.
  foreach (paragraphs_library_type_load() as $type_name => $info) {
    $items['admin/content/paragraphs/library/add/' . $type_name] = [
      'title' => t('Add a %type Paragraphs library item', ['%type' => $info->label]),
      'page callback' => 'paragraphs_library_item_add',
      'page arguments' => [$type_name],
      'access arguments' => ['create paragraphs_library_item entities'],
      'type' => MENU_CALLBACK,
    ];
  }

  $items['admin/content/paragraphs/library/%paragraphs_library_item'] = [
    'title callback' => 'paragraphs_library_item_page_title',
    'title arguments' => [4],
    'description' => t('View a saved Paragraphs library item.'),
    'page callback' => 'paragraphs_library_item_view',
    'page arguments' => [4],
    'access arguments' => ['view paragraphs_library_item entities'],
  ];

  $items['admin/content/paragraphs/library/%paragraphs_library_item/view'] = [
    'title' => t('View'),
    'page callback' => 'paragraphs_library_item_view',
    'page arguments' => [4],
    'access arguments' => ['view paragraphs_library_item entities'],
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  ];

  $items['admin/content/paragraphs/library/%paragraphs_library_item/edit'] = [
    'title' => t('Edit'),
    'description' => t('Edit a saved Paragraphs library item.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['paragraphs_library_item_form', 4],
    'access arguments' => ['edit paragraphs_library_item entities'],
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  ];

  $items['admin/content/paragraphs/library/%paragraphs_library_item/delete'] = [
    'title' => t('Delete'),
    'description' => t('Delete a Paragraphs library item.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['paragraphs_library_item_delete_form', 4],
    'access arguments' => ['edit paragraphs_library_item entities'],
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
  ];

  // Paragraphs library administration paths.
  $items['admin/structure/paragraphs/library/types'] = [
    'title' => t('Paragraphs library types'),
    'description' => t('List all types of Paragraphs library items.'),
    'page callback' => 'paragraphs_library_type_view',
    'access arguments' => ['administer paragraphs_library types'],
    'file' => 'paragraphs_library.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  ];

  $items['admin/structure/paragraphs/library/types/add'] = [
    'title' => t('Add a Paragraphs library type'),
    'description' => t('Form to create a Paragraphs library type.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['paragraphs_library_type_form', NULL],
    'access arguments' => ['administer paragraphs_library types'],
    'file' => 'paragraphs_library.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  ];

  $items['admin/structure/paragraphs/library/types/%paragraphs_library_type'] = [
    'title' => t('Paragraphs library type'),
    'title callback' => 'paragraphs_library_type_page_title',
    'title arguments' => [5],
    'description' => t('Provides an edit form for a Paragraphs library item type. This is where you will also find the Manage field and Manage display tabs.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['paragraphs_library_type_form', 5],
    'file' => 'paragraphs_library.admin.inc',
    'access arguments' => ['administer paragraphs_library types'],
    'type' => MENU_NORMAL_ITEM,
  ];

  // This item is here to create the "Info" tab.
  $items['admin/structure/paragraphs/library/types/%paragraphs_library_type/configure'] = [
    'title' => t('Configure'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'paragraphs_library.admin.inc',
  ];

  $items['admin/structure/paragraphs/library/types/%paragraphs_library_type/delete'] = [
    'title' => t('Delete library type'),
    'title callback' => 'paragraphs_library_type_page_title',
    'title arguments' => [5],
    'description' => t('Provides a delete form for a Paragraphs library item type.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['paragraphs_library_type_delete_form', 5],
    'file' => 'paragraphs_library.admin.inc',
    'access arguments' => ['administer paragraphs_library types'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function paragraphs_library_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['paragraphs_library_item'] = [
    'render element' => 'element',
    'template' => 'paragraphs-library-item',
    'path' => $path . '/theme',
    'file' => 'paragraphs_library.theme.inc',
    'attached' => [
      'css' => [
        $path . '/css/paragraphs-library-item.css',
      ],
    ],
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function paragraphs_library_permission() {
  $permissions = [
    'administer paragraphs_library types' => [
      'title' => t('Administer Paragraphs Library types'),
      'description' => t('Allows users to configure Paragraphs Library types and their fields.'),
      'restrict access' => TRUE,
    ],
    'create paragraphs_library_item entities' => [
      'title' => t('Create Paragraphs library items'),
      'description' => t('Allows users to create Paragraphs library items.'),
      'restrict access' => TRUE,
    ],
    'view own paragraphs_library_item entities' => [
      'title' => t('View own Paragraphs library items'),
      'description' => t('Allows users to view own Paragraphs library items.'),
      'restrict access' => TRUE,
    ],
    'view paragraphs_library_item entities' => [
      'title' => t('View Paragraphs library items'),
      'description' => t('Allows users to view Paragraphs library items.'),
      'restrict access' => TRUE,
    ],
    'edit any paragraphs_library_item entities' => [
      'title' => t('Edit any Paragraphs library items'),
      'description' => t('Allows users to edit any Paragraphs library items.'),
      'restrict access' => TRUE,
    ],
    'edit own paragraphs_library_item entities' => [
      'title' => t('Edit own Paragraphs library items'),
      'description' => t('Allows users to edit own Paragraphs library items.'),
      'restrict access' => TRUE,
    ],
  ];

  return $permissions;
}

/**
 * Displays a list of bundles to choose from, to create a new
 * paragraphs_library_item.
 */
function paragraphs_library_type_choice() {
  $library_types = paragraphs_library_type_load();
  if (count($library_types) == 1) {
    backdrop_goto('admin/content/paragraphs/library/add/' . reset($library_types)->type);
  }
  $items = [];
  backdrop_set_title(t('Select Paragraphs library type'), PASS_THROUGH);
  foreach ($library_types as $library_type_info) {
    $items[] = l($library_type_info->label, 'admin/content/paragraphs/library/add/' . $library_type_info->type);
  }
  return theme('item_list', ['items' => $items]);
}

/**
 * Form builder to edit paragraphs_library_items.
 */
function paragraphs_library_item_form($form, &$form_state, ?ParagraphsLibraryItem $paragraphs_library_item = NULL) {
  // Cache the object in $form_state for later retrieval.
  $form_state['paragraphs_library_item'] = $paragraphs_library_item;

  $form['title'] = [
    '#type' => 'textfield',
    '#title' => t('Admin label'),
    '#description' => t('By default this will only show in the administrative interfaces as an identifier for this library item.'),
    '#required' => TRUE,
    '#default_value' => (!$paragraphs_library_item->is_new) ? $paragraphs_library_item->label() : '',
  ];

  // Attaches Field API field widgets in this bundle to the form.
  field_attach_form('paragraphs_library_item', $paragraphs_library_item, $form, $form_state);

  $form['actions'] = [
    '#type' => 'actions',
    'submit' => [
      '#type' => 'submit',
      '#value' => t('Save'),
    ],
  ];

  return $form;
}

/**
 * Submit handler for the paragraphs_library_item form.
 *
 * Saves the paragraphs_library_item and its fields.
 */
function paragraphs_library_item_form_submit($form, &$form_state) {
  // Retrieve the cached paragraphs_library_item.
  $paragraphs_library_item = $form_state['paragraphs_library_item'];
  $paragraphs_library_item->title = $form_state['values']['title'];
  if (empty($paragraphs_library_item->created)) {
    // If this this is a new paragraphs_library_item, assign a created date.
    $paragraphs_library_item->created = REQUEST_TIME;
  }

  // Call this to attach the submitted field values to the
  // paragraphs_library_item entity.
  field_attach_submit('paragraphs_library_item', $paragraphs_library_item, $form, $form_state);

  $paragraphs_library_item->save();
  backdrop_set_message(t('The paragraphs_library_item has been saved'));
  $form_state['redirect'] = 'admin/content/paragraphs/library/' . $paragraphs_library_item->id();
}

/**
 * Page callback: Provides the Paragraphs library item submission form.
 *
 * @param string $type
 *   The Paragraphs library item type for the submission.
 *
 * @return array
 *   Returns a Paragraphs library item submission form.
 *
 * @see paragraphs_library_menu()
 */
function paragraphs_library_item_add(string $type) {
  global $user;

  $types = paragraphs_library_type_load();
  $paragraphs_library_item = entity_create('paragraphs_library_item', [
    'uid' => $user->uid,
    'title' => (isset($user->name) ? $user->name : ''),
    'type' => $type,
    'langcode' => LANGUAGE_NONE,
  ]);
  backdrop_set_title(t('Add a %type library item', ['%type' => t($types[$type]->label)]), PASS_THROUGH);
  $output = backdrop_get_form('paragraphs_library_item_form', $paragraphs_library_item);

  return $output;
}

/**
 * Confirm form to delete a paragraphs_library_item.
 */
function paragraphs_library_item_delete_form($form, &$form_state, ParagraphsLibraryItem $paragraphs_library_item) {
  // Send the paragraphs_library_item ID as a value field to the form.
  $form['paragraphs_library_item_id'] = [
    '#type' => 'value',
    '#value' => $paragraphs_library_item->id(),
  ];
  return confirm_form(
    $form,
    t('Are you sure you want to delete library item %title?', ['%title' => check_plain($paragraphs_library_item->label())]),
    'admin/content/paragraphs/library',
    t('This action cannot be undone and will affect all potential uses of this shared item throughout the site.'),
    t('Delete'),
    t('Cancel')
  );
}

/**
 * Submit handler for the paragraphs_library_item delete form.
 *
 * Deletes the paragraphs_library_item and displays a message.
 */
function paragraphs_library_item_delete_form_submit($form, &$form_state) {
  $paragraphs_library_item_id = $form_state['values']['paragraphs_library_item_id'];
  $paragraphs_library_item = entity_load('paragraphs_library_item', $paragraphs_library_item_id);
  entity_delete_multiple('paragraphs_library_item', [$paragraphs_library_item_id]);
  backdrop_set_message(t('Paragraphs library item %title has been deleted.', ['%title' => check_plain($paragraphs_library_item->label())]));
}

/**
 * Implements hook_entity_property_info_alter().
 *
 * This hook provides property definitions for metadata wrappers and views.
 */
function paragraphs_library_entity_property_info_alter(&$info) {
  $properties = &$info['paragraphs_library_info']['properties'];

  $properties['title'] = [
    'label' => t('Title'),
    'type' => 'text',
    'description' => t('The title of the paragraphs_library.'),
    'setter callback' => 'entity_plus_property_verbatim_set',
    'schema field' => 'title',
    // Tell i18n_string that this property is translatable.
    'translatable' => TRUE,
    'i18n string' => TRUE,
  ];

  $properties['created'] = [
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the paragraphs_library was posted."),
    'setter callback' => 'entity_plus_property_verbatim_set',
    'setter permission' => 'administer paragraphs_library entities',
    'schema field' => 'created',
  ];

  $properties['changed'] = [
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'setter callback' => 'entity_plus_property_verbatim_set',
    'description' => t("The date the paragraphs_library was most recently updated."),
  ];

  $properties['uid'] = [
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the paragraphs_library."),
    'setter callback' => 'entity_plus_property_verbatim_set',
    'setter permission' => 'administer paragraphs_library entities',
    'required' => TRUE,
    'schema field' => 'uid',
  ];
}

/*******************************************************************************
 ********************************* ParagraphsLibraryItem API's *****************
 ******************************************************************************/

/**
 * Access callback for paragraphs_library.
 */
function paragraphs_library_access($op, ?ParagraphsLibraryItem $paragraphs_library_item = NULL, $account = NULL, $entity_type = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }
  $access = FALSE;
  switch ($op) {
    case 'create':
      $access = user_access('administer paragraphs_library entities', $account)
          || user_access('create paragraphs_library entities', $account);
      break;
    case 'view':
      $access = user_access('administer paragraphs_library entities', $account)
          || user_access('view paragraphs_library entities', $account)
          || (user_access('view own paragraphs_library entities', $account) && ($paragraphs_library_item->uid == $account->uid));
      break;

    case 'update':
    case 'edit':
    case 'delete':
      $access = user_access('administer paragraphs_library entities')
          || user_access('edit any paragraphs_library entities')
          || (user_access('edit own paragraphs_library entities') && ($paragraphs_library_item->uid == $account->uid));
      break;
  }
  return $access;
}

/**
 * Load a paragraphs_library.
 */
function paragraphs_library_item_load($paragraphs_library_id, $reset = FALSE) {
  $entities = paragraphs_library_item_load_multiple([$paragraphs_library_id], [], $reset);
  return reset($entities);
}

/**
 * Load multiple paragraphs_library entities based on certain conditions.
 */
function paragraphs_library_item_load_multiple($paragraphs_library_ids = [], $conditions = [], $reset = FALSE) {
  return entity_load_multiple('paragraphs_library_item', $paragraphs_library_ids, $conditions, $reset);
}

/**
 * Save paragraphs_library.
 */
function paragraphs_library_item_save($paragraphs_library_item) {
  return entity_plus_save('paragraphs_library_item', $paragraphs_library_item);
}

/**
 * Delete single paragraphs_library.
 */
function paragraphs_library_item_delete($paragraphs_library_item) {
  entity_delete_multiple('paragraphs_library_item', [entity_plus_id('paragraphs_library_item', $paragraphs_library_item)]);
}

/**
 * Delete multiple paragraphs_library entities.
 */
function paragraphs_library_item_delete_multiple($paragraphs_library_ids) {
  entity_delete_multiple('paragraphs_library_item', $paragraphs_library_ids);
}

/**
 * Displays a Paragraphs library item.
 */
function paragraphs_library_item_view($paragraphs_library_item) {
  backdrop_set_title(check_plain($paragraphs_library_item->label()));
  $paragraphs_library_item_view = entity_view($paragraphs_library_item);
  return $paragraphs_library_item_view;
}

/**
 * Implements hook_views_api().
 *
 * This hook helps Backdrop discover the custom handlers in the /views folder.
 */
function paragraphs_library_views_api() {
  return [
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'paragraphs_library') . '/views',
  ];
}

/**
 * Implements hook_field_extra_fields().
 *
 * This exposes the "extra fields" (usually properties that can be configured
 * as if they were fields) of the entity as pseudo-fields
 * so that they get handled by the Entity and Field core functionality.
 */
function paragraphs_library_field_extra_fields() {
  $extra_fields = [];

  $display['title'] = [
    'weight' => -10,
    'label' => t('Title'),
    'description' => t('The title of the Paragraphs library item.'),
  ];

  $form['title'] = [
    'weight' => -10,
    'label' => t('Title'),
    'description' => t('The title of the Paragraphs library item.'),
  ];

  $display['uid'] = [
    'label' => t("Author"),
    'weight' => -11,
    'description' => t("The author of the Paragraphs library item."),
  ];

  $display['created'] = [
    'label' => t("Date created"),
    'weight' => 0,
    'description' => t("The date the Paragraphs library item was posted."),
  ];

  $display['changed'] = [
    'label' => t("Date changed"),
    'weight' => 1,
    'description' => t("The date the Paragraphs library item was changed."),
  ];

  return $extra_fields;
}

/**
 * Implements template_proprocess_entity_plus_property().
 *
 * This is used to convert the Date created and Date changed properties into
 * a proper date format. Ideally this would be done via UI, but Entity Plus
 * or Backdrop do not provide a way to do this for properties through the
 * Manage fields tab.
 */
function paragraphs_library_preprocess_entity_plus_property(&$variables) {
  if ($variables['property_name'] == 'created' || $variables['property_name'] == 'changed') {
    $variables['content'] = format_date($variables['content']);
  }
}

/**
 * Loads and returns type/bundle information for Paragraphs library items.
 *
 * @param string $type
 *   This is the machine name of the bundle as defined in the entity_info. By
 *   default 'default'. If empty, returns an array of all bundles.
 *
 * @param bool $reset
 *   If TRUE, the static cache is reset and the bundles are reloaded from
 *   configuration.
 *
 * @return object|array|FALSE
 *   Either a stdClass object with bundle info (machine name and label) or an
 *   array of such objects if $type is not specified. If $type is specified
 *   and does not exist, FALSE is returned.
 */
function paragraphs_library_type_load(string $type = '', bool $reset = FALSE) {
  // Since this function is called very often, use a static cache.
  $all_types = &backdrop_static(__FUNCTION__, []);
  if (empty($all_types) || $reset) {
    $all_types = [];
    $configs = config_get_names_with_prefix('paragraphs_library.type.');
    foreach ($configs as $config_name) {
      $config = config($config_name);
      $type_str = strtr($config->get('type'), array('_' => '-'));
      $all_types[$type_str] = (object) $config->get();
    }
  }
  return empty($type) ? $all_types : $all_types[$type] ?? FALSE;
}

/**
 * Title callback for Paragraphs library item administration pages.
 */
function paragraphs_library_item_page_title($paragraphs_library_item) {
  return $paragraphs_library_item->title ? $paragraphs_library_item->title : t('Paragraphs library item @id', ['@id' => $paragraphs_library_item->id()]);
}


/**
 * Title callback for Paragraphs library type administration pages.
 */
function paragraphs_library_type_page_title($paragraphs_library_type) {
  return $paragraphs_library_type->label;
}
