<?php
/**
 * @file
 * Paragraphs library install and update hooks.
 */

/**
 * Implements hook_schema().
 */
function paragraphs_library_schema() {
  $schema = [];

  // This table will hold Paragraphs library item entities.
  $schema['paragraphs_library_item'] = [
    'description' => 'The base table for Paragraphs library item entities.',
    'fields' => [
      'paragraphs_library_id' => [
        'description' => 'The primary identifier for the Paragraphs library item.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'type' => [
        'description' => 'The type (bundle) of this Paragraphs library item.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ],
      'title' => [
        'description' => 'The title of the Paragraphs library item.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ],
      'description' => [
        'description' => 'A description of the Paragraphs library item.',
        'type' => 'text',
      ],
      'uid' => [
        'description' => 'ID of Backdrop account that created this Paragraphs library item.',
        'type' => 'int',
        'not null' => TRUE,
      ],
      'created' => [
        'description' => 'The Unix timestamp when the Paragraphs library item was created.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
      'changed' => [
        'description' => 'The Unix timestamp when the Paragraphs library item was most recently saved.',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['paragraphs_library_id'],
  ];

  return $schema;
}

/**
 * Implements hook_install().
 */
function paragraphs_library_install() {
  user_role_grant_permissions(BACKDROP_AUTHENTICATED_ROLE, [
    // Grant viewing permision to authenticated users.
    'view paragraphs_library entities',
  ]);
}

/**
 * Implements hook_uninstall().
 */
function paragraphs_library_uninstall() {
  // Remove the view showing Paragraphs library item entities.
  $config = config('views.view.paragraphs_library');
  $config->delete();

  // Get all Paragraphs library types/bundles.
  include_once backdrop_get_path('module', 'paragraphs_library') . '/paragraphs_library.module';
  $library_types = paragraphs_library_type_load();
  foreach ($library_types as $library_type) {
    // Instruct field.module to remove fields attached to these library types.
    field_attach_delete_bundle('paragraphs_library_item', $library_type);
  }

  menu_rebuild();
}
