<?php
/**
 * @file
 * Provides configurable Paragraphs layout templates.
 *
 * This provides the UI to list, create, edit and delete Paragraphs layouts.
 */

require_once dirname(__FILE__) . '/layout_paragraphs.field_widget.inc';

/**
 * Implements hook_permission().
 */
function layout_paragraphs_permission() {
  $perms = array(
    'administer layout paragraphs' => array(
      'title' => t('Administer Layout Paragraphs'),
      'description' => t('Is able to administer Layouts for the Paragraphs module'),
    ),
  );
  return $perms;
}

/**
 * Implements hook_menu().
 */
function layout_paragraphs_menu() {
  $items = array();
  $items['admin/structure/paragraphs/layouts'] = array(
    'title' => 'Layout Paragraphs',
    'description' => 'Manage layouts for use with Paragraphs',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_listing_page'),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/add'] = array(
    'title' => 'Add Paragraphs layout template',
    'page callback' => 'layout_paragraphs_template_settings_add_form',
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore'] = array(
    'title' => 'Edit Paragraphs layout template settings',
    'title callback' => 'layout_paragraphs_template_title_callback',
    'title arguments' => array(5),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_settings_edit_form', 4),
    'access arguments' => array('administer layout paragraphs'),
    'file' => 'layout_paragraphs.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/edit'] = array(
    'title' => 'Edit Paragraphs layout template settings',
    'title callback' => 'layout_paragraphs_template_title_callback',
    'title arguments' => array(5),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_settings_edit_form', 4),
    'access arguments' => array('administer layout paragraphs'),
    'file' => 'layout_paragraphs.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/configure'] = array(
    'title' => 'Configure Paragraphs layout template regions',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_configure_form', 4),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/delete'] = array(
    'title' => 'Delete Paragraphs layout template',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_delete_form', 4),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/row/%/delete'] = array(
    'title' => 'Delete row',
    'page callback' => 'layout_paragraphs_template_delete_row',
    'page arguments' => array(4, 6),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_CALLBACK,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/row/%/select-widths'] = array(
    'title' => 'Choose region widths',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_region_style_select', 4, 6),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_CALLBACK,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/row/%/configure'] = array(
    'title' => 'Add row',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_edit_row_form', 4, 6),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_CALLBACK,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );

  $items['admin/structure/paragraphs/layouts/%layout_paragraphs_tempstore/row/%/configure/%'] = array(
    'title' => 'Add row',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_template_edit_row_form', 4, 6, 8),
    'access arguments' => array('administer layout paragraphs'),
    'type' => MENU_CALLBACK,
    'weight' => -10,
    'file' => 'layout_paragraphs.admin.inc',
  );
  $base = array(
    'access arguments' => array('administer layout paragraphs'),
    'theme callback' => 'ajax_base_page_theme',
  );
  $items['admin/structure/paragraphs/layouts/manage/%layout_paragraphs_instance_tempstore/add-block/%/%'] = array(
    'title callback' => 'layout_paragraphs_block_add_title',
    'title arguments' => array(5, 7, 8),
    'page callback' => 'layout_paragraphs_block_add_page',
    'access arguments' => array('administer layout paragraphs'),
    'page arguments' => array(5, 7, 8),
    'file' => 'layout_paragraphs.admin.inc',
  ) + $base;
  $items['admin/structure/paragraphs/layouts/manage/%layout_paragraphs_instance_tempstore/configure-region/%/%'] = array(
    'title' => 'Configure region',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('layout_paragraphs_configure_region_page', 5, 7 , 8),
    'access arguments' => array('administer layout paragraphs'),
    'file' => 'layout_paragraphs.admin.inc',
  ) + $base;

  return $items;
}

/**
 * Implements hook_entity_delete().
 *
 * Remove layout_paragraphs entries when the entity is deleted.
 *
 */
function layout_paragraphs_entity_delete($entity, $entity_type) {
  $layout_paragraphs_id = db_select('layout_paragraphs', 'lp')
    ->fields('lp', array('id'))
    ->condition('entity_id', $entity->id())
    ->condition('entity_type', $entity_type)
    ->condition('bundle', $entity->bundle())
    ->execute()
    ->fetchField();
  if ($layout_paragraphs_id) {
    db_delete('layout_paragraphs')
      ->condition('id', $layout_paragraphs_id)
      ->execute();
  }
  db_delete('layout_paragraphs_blocks')
    ->condition('lp_id', $layout_paragraphs_id)
    ->execute();
}

/**
 * Load a Layout Paragraphs layout by name.
 *
 * @param string $layout_paragraphs_template_name
 *   The concatenated machine name of the layout template to load.
 *   Example: 'node.page.field_layout_paragraphs.123'.
 *
 * @return Layout
 *  The loaded layout object.
 */
function layout_paragraphs_layout_load(string $layout_paragraphs_template_name) {
  module_load_include('inc', 'layout_paragraphs', 'layout_paragraphs.admin');

  list($entity_type, $bundle, $field_name, $entity_id) = explode('.', $layout_paragraphs_template_name);
  $query = db_select('layout_paragraphs', 'lp')
    ->fields('lp')
    ->condition('lp.entity_type', $entity_type)
    ->condition('lp.bundle', $bundle)
    ->condition('lp.field_name', $field_name)
    ->condition('lp.entity_id', $entity_id);
  $result = $query->execute()->fetchAssoc();
  $template_name = $result['layout_template'];
  $config = array(
    'is_new' => TRUE,
    'layout_template_type' => 'paragraphs',
    'is_full_page' => FALSE,
    'name' => $layout_paragraphs_template_name,
  );
  $layout = new Layout($config);
  $layout->setContexts('paragraphs', layout_paragraphs_context());
  $layout->setLayoutTemplate($template_name);

  return $layout;
}


/**
 * Store changes to a flexible layout template in the temporary store.
 *
 * @param LayoutFlexibleTemplate $flexible_template
 *   The loaded flexible template object.
 * @param string $flexible_template_type
 *   The type of flexible template to save. Defaults to 'flexible'.
 */
function layout_paragraphs_tempstore_set(LayoutFlexibleTemplate $flexible_template) {
  layout_flexible_tempstore_set($flexible_template, 'paragraphs');
}

/**
 * Get a layout paragraphs template currently being edited from the tempstore.
 *
 * If a template is not yet being edited, the template will be loaded from
 * configuration.
 *
 * @param string $flexible_template_name
 *   The machine name of the flexible template to load.
 *
 * @return LayoutFlexibleTemplate
 *   The flexible template object.
 */
function layout_paragraphs_tempstore_load(string $flexible_template_name) {
  return layout_flexible_tempstore_load($flexible_template_name, 'paragraphs');
}

/**
 * Get a layout paragraphs instance currently being edited from the tempstore.
 *
 * If an instance is not yet being edited, the instance will be loaded from
 * configuration.
 *
 * @param string $flexible_template_name
 *   The machine name of the flexible template to load.
 *
 * @return Layout
 *   The Layout paragraphs instance.
 */
function layout_paragraphs_instance_tempstore_load($instance_name = NULL) {
  if (empty($instance_name)) {
    return NULL;
  }
  $layout = layout_paragraphs_tempstore_load($instance_name);
  if (!empty($layout)) {
    return $layout;
  }
  $layout = layout_paragraphs_layout_load($instance_name, TRUE);
  return (!empty($layout)) ? $layout : NULL;
}

/**
 * Helper to get the title of a Paragraphs layout template.
 *
 * @param object $template
 *   The object of the template to get the title for.
 */
function layout_paragraphs_template_title_callback($template) {
  return t('!name', array('!name' => $template->title));
}

/**
 * Implements hook_theme().
 */
function layout_paragraphs_theme() {
  return array(
    'layout_paragraphs_template_info' => array(
      'variables' => array('template_info' => NULL),
      'path' => backdrop_get_path('module', 'layout_paragraphs') . '/theme',
      'file' => 'layout_paragraphs.theme.inc',
    ),
    'layout_paragraphs_template_style_option' => array(
      'variables' => array('row_style' => NULL),
      'path' => backdrop_get_path('module', 'layout_paragraphs') . '/theme',
      'file' => 'layout_paragraphs.theme.inc',
    ),
    'layout_paragraphs_template_option' => array(
      'variables' => array('template_info' => NULL),
      'path' => backdrop_get_path('module', 'layout_paragraphs') . '/theme',
      'file' => 'layout_paragraphs.theme.inc',
    ),
  );
}

/**
 * Helper to insert a new layout_paragraphs entry when one does not exist.
 *
 * @return int
 *  The ID of the new entry, or 0 if it was unsuccessful.
 */
function layout_paragraphs_entity_template_insert(int $entity_id, string $entity_type, string $bundle, string $field_name, string $selected_template) {
  $lp_id = db_insert('layout_paragraphs')
    ->fields(array(
      'entity_id' => $entity_id,
      'entity_type' => $entity_type,
      'bundle' => $bundle,
      'field_name' => $field_name,
      'module' => 'layout_paragraphs',
      'layout_template' => $selected_template,
    ))
    ->execute();
  return (!empty($lp_id) && is_numeric($lp_id)) ? $lp_id : 0;
}

/**
 * Implements hook_layout_renderer_info().
 */
function layout_paragraphs_layout_renderer_info() {
  $info = array(
    'paragraphs' => array(
      'class' => 'LayoutRendererParagraphs',
    ),
    'paragraphs_editor' => array(
      'class' => 'LayoutRendererEditorParagraphs',
    ),
  );
  return $info;
}

/**
 * Implements hook_layout_style_info().
 */
function layout_paragraphs_layout_style_info() {
  $info['paragraphs'] = array(
    'title' => t('Paragraphs'),
    'description' => t('The default Paragraphs block rendering style.'),
    'block theme' => 'block',
    'class' => 'LayoutStyleParagraphs',
    'template' => 'templates/block_paragraphs',
    'file' => 'layout_paragraphs.theme.inc',
  );
  // @todo: add a 'paragraphs_editor' style for the editor which uses preview mode?
  return $info;
}

/**
 * Implements hook_config_info().
 */
function layout_paragraphs_config_info() {
  $prefixes['layout.paragraphs'] = array(
    'name_key' => 'name',
    'label_key' => 'title',
    'group' => t('Layout Paragraphs'),
  );
  return $prefixes;
}

/**
 * Implements hook_layout_context_info().
 */
function layout_paragraphs_layout_context_info() {
  $info['paragraphs'] = array(
    'title' => t('Paragraphs'),
    'class' => 'ParagraphsLayoutContext',
    'menu paths' => array(),
  );
  return $info;
}

/**
 * Implements hook_layout_relationship_info().
 */
// @todo relationships needed? E.g. host entity from paragraph?
/*
function layout_paragraphs_layout_relationship_info() {
  $info['author_from_node'] = array(
    'title' => t('Author of content'),
    'class' => 'LayoutRelationshipAuthorFromNode',
    'context' => 'node',
    'context_label' => t('Content'),
    'description' => t('Creates a user context from the author of a piece of content.'),
  );

  return $info;
}
*/

/**
 * Alters the list of flexible layout types to add Layout Paragraphs.
 */
function layout_paragraphs_layout_flexible_types_alter(&$types) {
  $types['paragraphs'] = t('Layout Paragraphs');
}

/**
 * Reset all caches provided by Layout Paragraphs module.
 */
function layout_paragraphs_reset_caches() {
  cache()->delete('layout:paragraphs:config');
  backdrop_static_reset('layout_flexible_template_load_all:paragraphs');
  backdrop_static_reset('layout_flexible_tempstore_load:paragraphs');
}

/**
 * Implements hook_autoload_info().
 */
function layout_paragraphs_autoload_info() {
  return array(
    'LayoutRendererParagraphs' => 'plugins/renderers/layout_renderer_paragraphs.inc',
    'LayoutRendererEditorParagraphs' => 'plugins/renderers/layout_renderer_editor_paragraphs.inc',
    'BlockParagraphs' => 'includes/block.paragraphs.inc',
    'ParagraphsLayoutContext' => 'includes/paragraphs_layout_context.inc',

    // Styles.
    'LayoutStyleParagraphs' => 'plugins/styles/layout_style_paragraphs.inc',
  );
}

/**
 * Implements hook_block_info().
 */
function layout_paragraphs_block_info() {
  $blocks = array();

  // Layout Paragraphs blocks.
  $blocks['paragraph'] = array(
    'info' => t('Paragraph'),
    'description' => t('Placeholder for Paragraphs block.'),
    'class' => 'BlockParagraphs',
    'required contexts' => array('paragraphs' => 'paragraphs'),
  );
  return $blocks;
}

/**
 * Load the information of either a single Layout Paragraphs template or all
 * available Layout Paragraphs templates.
 *
 * @param string $template_name
 *   Optionally specify a name of a single Layout Paragraphs template, e.g.
 *   "default". If no template name is specified, information for all
 *   Layout Paragraphs templates will be returned.
 *
 * @param boolean $rebuild
 *   Whether the list of layout template info needs to be rebuilt (see
 *   https://github.com/backdrop/backdrop-issues/issues/984). The rebuild is
 *   required only on specific cases, so this defaults to FALSE. That way, the
 *   rest of the times the layout cache is used (when available) for performance
 *   reasons.
 *
 * @return array
 *   The Layout Paragraphs template information. We aren't using
 *   hook_layout_template_info() because we're keeping these layouts out of the
 *   main Layout UI.
 */
function layout_paragraphs_get_layout_template_info($template_name = NULL, $rebuild = FALSE) {
  $info = &backdrop_static(__FUNCTION__);

  // Try getting a cached list of layout info.
  if (!isset($info) && !$rebuild) {
    $cache = cache('cache')->get('layout_paragraphs_info');

    if ($cache && $cache->data) {
      $info = $cache->data;
    }
  }

  // Rebuild the list of layout info.
  if (!isset($info[$template_name]) || $rebuild) {
    $info = array();
    $styles = layout_flexible_row_styles();

    $layout_paragraphs_templates = layout_flexible_template_load_all('paragraphs');
    foreach ($layout_paragraphs_templates as $layout_paragraphs_template) {
      $info[$layout_paragraphs_template->name] = array(
        'title' => $layout_paragraphs_template->title,
        'name' => $layout_paragraphs_template->name,
        'regions' => array(),
        'default region' => '',
        'template' => 'layout--flexible',
        'path' => backdrop_get_path('module', 'layout') . '/templates',
        'flexible' => TRUE,
        'layout_template_type' => 'paragraphs',
        'is_full_page' => FALSE,
        'module' => 'layout_paragraphs',
        'preview' => "<svg width='50' height='75'><rect x='0' y='0' width='50' height='75' fill='rgb(102, 102, 102)' /><rect x='52' y='0' width='52' height='75' fill='rgb(102, 102, 102)' /></svg>",
      );

      foreach ($layout_paragraphs_template->rows as $row_name => $region) {
        $region_style = $styles[$region['contains']];
        for ($i = 0; $i < $region_style['region_count']; $i++) {
          if (!empty($region['region_names']['region_' . $i]['label'])) {
            $region_name = $region['region_names']['region_' . $i]['label'];
          }
          else {
            $region_name = $row_name . ' ' . $i;
          }
          $info[$layout_paragraphs_template->name]['regions'][$row_name . '--' . $i] = $region_name;
        }
      }
    }
    // Populate defaults.
    foreach ($info as $name => $layout_info) {
      $info[$name] += array(
        'hidden' => FALSE,
        'preview' => "<svg width='50' height='75'><rect x='0' y='0' width='50' height='75' fill='rgb(102, 102, 102)' /></svg>",
        'default region' => 'content',
        'stylesheets' => array(
          'all' => array(str_replace('_', '-', $name) . '.css'),
        ),
      );
      if (!isset($info[$name]['template'])) {
        $template_path = BACKDROP_ROOT . '/' . $layout_info['path'] . '/layout--' . str_replace('_', '-', $name) . '.tpl.php';

        if (is_file($template_path)) {
          $info[$name]['template'] = 'layout--' . str_replace('_', '-', $name);
        }
      }
    }

    // Sort the available layouts by display name.
    backdrop_sort($info, array('title' => SORT_STRING));

    cache('cache')->set('layout_paragraphs_info', $info);
  }

  if ($template_name) {
    if (isset($info[$template_name])) {
      return $info[$template_name];
    }
    else {
      return [];
    }
  }
  else {
    return $info;
  }
}

/**
 * Implements hook_field_update_field().
 *
 * Make changes after a Layout Paragraphs-enabled field is updated.
 */
function layout_paragraphs_field_update_field($field, $prior_field, $has_data) {
  $pause = 1;
  // @todo: update the field's layout template settings (is this needed here?)
}

/**
 * Helper: return a field instance based on a Layout Paragraphs layout name.
 *
 * @param string $layout_name
 *  The name of the layout to get the field instance for.
 *
 * @return array
 *  The field instance array, or an empty array if not found.
 */
function _layout_paragraphs_get_field_instance(string $layout_name) {
  list($entity_type, $bundle, $field_name, $entity_id) = explode('.', $layout_name);
  if (empty($entity_type) || empty($bundle) || empty($field_name)) {
    return [];
  }
  $field_instance = field_info_instance($entity_type, $field_name, $bundle);
  return $field_instance ?? [];
}

/**
 * Helper: return a Layout Paragraphs layout name based on a field instance.
 *
 * @param array $field_instance
 *  The field instance array.
 * @param int $entity_id
 *  The entity ID of the layout in question.
 *
 * @return string
 *  The name of the layout based on the field instance for, or an empty string
 *  if unsuccessful.
 */
function _layout_paragraphs_get_layout_name(array $field_instance, int $entity_id) {
  if (
    empty($field_instance['entity_type'])
    || empty($field_instance['bundle'])
    || empty($field_instance['field_name'])
    || $entity_id <= 0) {
    return '';
  }
  return $field_instance['entity_type'] . '.' . $field_instance['bundle'] . '.' . $field_instance['field_name'] . '.' . $field_instance['entity_id'];
}

/**
 * Helper: Get the LP Id based on the layout name.
 *
 * @param string $layout_name
 * The name of the layout to get the LP ID for.
 *
 * @return int
 *
 */
function _layout_paragraphs_get_lp_id(string $layout_name) {
  list($entity_type, $bundle, $field_name, $entity_id) = explode('.', $layout_name);
  if (empty($entity_type) || empty($bundle) || empty($field_name) || empty($entity_id)) {
    return 0;
  }
  $query = db_select('layout_paragraphs', 'lp')
    ->fields('lp', array('id'))
    ->condition('lp.entity_type', $entity_type)
    ->condition('lp.bundle', $bundle)
    ->condition('lp.field_name', $field_name)
    ->condition('lp.entity_id', $entity_id);
  $lp_id = $query->execute()->fetchField();

  return (!empty($lp_id) && is_numeric($lp_id)) ? $lp_id : 0;
}
